### ISSUE TITLE
Incosistency in shared library versioning

### ISSUE THREAD

**Issue by pcpa** [pynac/pynac#101]
Currently Fedora has pynac-0.3.2, that installs:
```
%{_libdir}/libpynac.so.1.1.0
%{_libdir}/libpynac.so.1
```
  I am in the process of updating to match a newer sagemath package,
but it will install:
```
%{_libdir}/libpynac.so.1.1.0
%{_libdir}/libpynac.so.1
```

The problem is that pynac-0.3.2 had this chunk in configure.ac:
```
m4_define([ginac_major_version], [0])
m4_define([ginac_minor_version], [3])
m4_define([ginac_micro_version], [2])
m4_define([ginac_version], [ginac_major_version.ginac_minor_version.ginac_micro_version])
m4_define([ginac_release], [ginac_major_version.ginac_minor_version])
m4_define([ginac_interface_age], [0])
m4_define([ginac_binary_age], [1])
...
m4_define([lt_revision], [ginac_interface_age])
m4_define([lt_current], [m4_eval(ginac_micro_version - ginac_interface_age)])
m4_define([lt_age], [m4_eval(ginac_binary_age - ginac_interface_age)])
LT_VERSION_INFO="lt_current:lt_revision:lt_age"
```

while newer pynac does not have the "complex" versioning logic.

This issue is just to ask for some feedback about it. Currently only the sagemath package should require pynac in Fedora, so I can do a shared library "unbump".

**Comment by rwst** [comment]
You're right. This was changed in 10b010a and I never noticed the wrong LT version.

**Comment by rwst** [comment]
As long as you can "unbump" there is no urgency here. However, I tried to set `lt_revision` to 1 and got libpynac-0.0.1 which is wrong. So, there is a bug which must be fixed even if one wants to use the current simplified version manually.

**Comment by rwst** [comment]
With 6e522c2 we are now starting to change shared library versions. Be aware that API changes may be quite frequent.

**Comment by pcpa** [comment]
Ok. I will reset the version of the shared library, as it is not tied with the rpm version.
There is only sagemath and "self" dependency:
```
$ dnf repoquery --provides pynac
libpynac.so.1
libpynac.so.1()(64bit)
pynac = 0.3.2-7.fc23
pynac(x86-32) = 0.3.2-7.fc23
pynac(x86-64) = 0.3.2-7.fc23
$ dnf repoquery --whatrequires 'libpynac.so.1()(64bit)'
pynac-devel-0:0.3.2-7.fc23.x86_64
sagemath-core-0:6.5-14.fc24.x86_64
```
I am finally finishing an intermediate update of the sagemath package for Fedora. So, will use the opportunity to update pynac in rawhide.
