### ISSUE TITLE
sign confusion for infinity

### ISSUE THREAD

**Issue by behackl** [pynac/pynac#123]
While

    sage: exp(-oo)
    0

works as expected,

    sage: exp(-x).subs(x=oo)

raises [the error with `unsigned_infinity`](https://github.com/pynac/pynac/blob/master/ginac/inifcns_trans.cpp#L75-L81). This is http://trac.sagemath.org/ticket/19918.

**Comment by behackl** [comment]
I've tried to trace this, but unfortunately I do not understand the mechanisms behind pynac's handling of infinity sufficiently.

However, I found that in the scenario above, although neither `x.is_equal(Infinity)` nor `x.is_equal(NegInfinity)` yields true, `x` is also not unsigned infinity: in fact, `(-x).is_equal(Infinity)` yields true...

A workaround would be to check for `(-x).is_equal(Infinity)` and `(-x).is_equal(NegInfinity)` -- but I don't think that this is the way to go.

**Comment by rwst** [comment]
```
(gdb) p x.dbgprinttree()
infinity (infinity) @0x2da74b0, hash=0x25b6d6b4, flags=0xf
    -1 (numeric) @0x16b8670, hash=0x0, flags=0x7
```
So `x` should equal `-oo` but the check for this using `is_equal` stopped working. Also the code itself should not assume it's unsigned infinity if it's neither plus or minus.

**Comment by rwst** [comment]
The obvious reason is
```
sage: hash(SR(-oo))
2886518159
sage: hash((-x).subs(x=oo))
81231252
sage: hash((x).subs(x=-oo))
2886518159
sage: hash(-oo)
-9223372036854775808
```

**Comment by behackl** [comment]
Does that mean that `is_equal` also works again properly as soon as the hashes are fixed? If so, then this is probably a sage-thing and this issue could be closed.

**Comment by rwst** [comment]
No. This is independent from the Sage tickets 19927 and 19928.
