### ISSUE TITLE
zeta series expansion at symbolic constants

### ISSUE THREAD

**Issue by behackl** [pynac/pynac#128]
```
sage: zeta(x).series(x==pi, 2)
Traceback (most recent call last):
...
RuntimeError: stub
```

This is most likely because [here](https://github.com/pynac/pynac/blob/master/ginac/inifcns_zeta.cpp#L170) conversion to a numeric is done and pynac doesn't really like that when something like `pi` comes along. I'm rather sure that this can be fixed by checking whether the expression is equal to `_ex1`.

**Comment by behackl** [comment]
This is now [Trac #20082](http://trac.sagemath.org/ticket/20082).

**Comment by rwst** [comment]
The actual reason is an old bug: not checking if `ex` is a numeric before doing `ex_to<numeric>`. I'll scan the code for similar cases.
In the PR there are good reasons to use `ex::is_integer_one()` instead of `is_equal(_ex1)` but I think it makes no difference here.
