### ISSUE TITLE
let sin/cos evaluate (assumed integer)*pi

### ISSUE THREAD

**Issue by behackl** [pynac/pynac#130]
IMHO, something like
```
sage: var('k')
k
sage: assume(k, 'integer')
sage: sin(k*pi)
0
sage: cos(k*pi)
(-1)^k
sage: cos(2*k*pi)
1
sage: cos(2*k*pi + pi)
-1
sage: tan(k*pi)
0
```
should work.

I've accomplished something that behaves similarly by adding checks like
```
	const ex ExOverPi = x/Pi;
	if (ExOverPi.info(info_flags::integer))
		return _ex0;
```
but I'm not sure whether this is a good or even viable approach. (On the other hand, the integer-flag is there to use it. Probably. ;-))

**Comment by rwst** [comment]
If you can combine this with the existing logic for trig functions of rational multiple of pi argument then I'm all for it. I.e. it should also resolve `sin(2*pi*k+pi/30)` to `-1/8*sqrt(5) + 1/2*sqrt(-3/8*sqrt(5) + 15/8) - 1/8
`

**Comment by behackl** [comment]
I agree that this would be nice. Not sure yet of how to accomplish this, but I'll think about it.

**Comment by behackl** [comment]
Here is what I came up with so far:

I'd like to reduce the argument mod `2*pi`, but with the restriction that the argument might not be numeric. With `x.coeff(Pi)`, the coefficient of `pi` can be extracted---however, I haven't found a good way to iterate trough the summands of whatever the coefficient of `pi` might be. If I can do that, then I could remove all even integers.

The logic for the `sin(k*pi)` etc. would have to be added in any case, as the argument is not numeric and thus the existing logic cannot be used directly.

Any idea how I can go through the summands? Somehow with `op(...)` and additionally checking with `is_a<add>`, if that even works?

**Comment by rwst** [comment]
If the argument is a sum (expand it beforehand) then it is of type `Add`. `expairseq`s like `Add` and `Mul` have their operands in a member variable of type `epvector`, a vector of `expair`s which can be queried with `op()`. There is additionally an `overall_coeff` that although of type `ex` is always a `numeric` I think. That should be sufficient to get the residue which then would be multiplied with `60/pi` as in the existing logic.
