### ISSUE TITLE
argument simplification (period reduction) for exp

### ISSUE THREAD

**Issue by behackl** [pynac/pynac#133]
This is something that might be worth considering: similar to what has been done for #130, an analogous thing could be done for `exp`: the period in this case is complex with `2*pi*I`, and maybe a similar strategy could be used to reduce the period.

This would result in something like
```
sage: exp(1 + 2*pi*I)
e
```
and even
```
sage: exp(1 + 2*pi*I*k)
e
```

That is, if we want that to happen.

**Comment by rwst** [comment]
I cannot see arguments against it, do you? SymPy is inconsistent and Maxima is reluctant:
```
In [5]: sin(2*n*pi)
Out[5]: 0

In [6]: sin(2*n*pi+1)
Out[6]: sin(2⋅π⋅n + 1)

In [7]: exp(2*n*I*pi)
Out[7]:
 2⋅ⅈ⋅π⋅n
ℯ

In [8]: exp(2*n*I*pi+1)
Out[8]:
 2⋅ⅈ⋅π⋅n + 1
ℯ

(%i2) declare(n, integer);
(%o2)                                done
(%i3) sin(n*pi);
(%o3)                              sin(n pi)
(%i4) sin(2*n*pi);
(%o4)                             sin(2 n pi)
(%i5) exp(2*n*pi*I);
                                    2 n pi I
(%o5)                             %e
```
