### ISSUE TITLE
simplification of powers/bases

### ISSUE THREAD

**Issue by behackl** [pynac/pynac#134]
This is something related to [trac #20084](http://trac.sagemath.org/20084) I'd like to discuss:

Should there be a mechanism that simplifies an expression like `base^(something/log(base))` to `exp(something)`?

As far as I can tell, this would resolve the ticket above. But I'm not sure whether this is a good approach.

**Comment by rwst** [comment]
How does SymPy do it?
```
In [15]: residue(f,x,2*pi*I/log(2))
Out[15]:
  1
──────
log(2)
```

**Comment by behackl** [comment]
SymPy seems to reduce it automatically:

```
>>> 2 ** (1/log(2))
E
```

**Comment by rwst** [comment]
Yes, I think we should do it.

**Comment by behackl** [comment]
Note that the pull request is not merged yet! :wink:

**Comment by rwst** [comment]
ah well..
