### ISSUE TITLE
series expansion of powers of functions with known expansion

### ISSUE THREAD

**Issue by behackl** [pynac/pynac#135]
Once again, the problem lies at the poles:

```
sage: (zeta(x)^2).series(x==1, 2)
(Infinity) + (Infinity)*(x - 1) + Order((x - 1)^2)
sage: (gamma(x)^2).series(x==0, 2)
Traceback (most recent call last):
...
ValueError: psi_eval(): simple pole
sage: (tan(x)^2).series(x==pi/2,2)
(Infinity) + (Infinity)*(-1/2*pi + x) + Order(1/4*(pi - 2*x)^2)
```
The proper expansion could be obtained by expanding before taking the power:
```
sage: ((zeta(x).series(x==1, 2))^2).series(x==1)
1*(x - 1)^(-2) + (2*euler_gamma)*(x - 1)^(-1) + (euler_gamma^2 - stieltjes(1)) + Order(x - 1)
sage: ((gamma(x).series(x==0, 2)^2)).series(x==0)
1*x^(-2) + (-2*euler_gamma)*x^(-1) + (2*euler_gamma^2 + 1/6*pi^2) + Order(x)
sage: ((tan(x).series(x==pi/2, 2)^2)).series(x==pi/2)
1*(-1/2*pi + x)^(-2) + (-2/3) + Order(-1/2*pi + x)
```

Is it possible to adapt the `series`-method to check for powers of known functions?

**Comment by rwst** [comment]
From the comments in https://github.com/pynac/pynac/blob/master/ginac/pseries.cpp#L1084 it seems handled. Can you make sense of the code?

**Comment by behackl** [comment]
Interesting! Haven't seen that before; maybe the exception isn't raised properly. I'll investigate.

**Comment by behackl** [comment]
It seems the problem arises because we return `Infinity` instead of raising a `pole_error`.

I'll propose a fix for this.

**Comment by rwst** [comment]
`return *Infinity` happens in a lot of places...

**Comment by behackl** [comment]
No, not for returning `Infinity`. Actually I prefer that the following works:
```
sage: zeta(1)
Infinity
sage: gamma(0)
Infinity
```
IMHO, `pseries` should just check whether substitution yields infinity. Thats a rather manageable fix. ;-)
