### ISSUE TITLE
positivity of converted finite field elements

### ISSUE THREAD

**Issue by behackl** [pynac/pynac#143]
Not sure whether the following behavior is actually intended:
```
sage: k.<a> = GF(27)
sage: SR(a^2 + 2*a + 1)._dbgprinttree()
a^2 + 2*a + 1 (numeric) @0x34774a0, hash=0x0, flags=0x7
```
This might come from the fact that
```
sage: SR.has_coerce_map_from(k)
True
```
and thus `a^2 + 2*a + 1` is seen as a numeric element of `SR`... nevertheless, this introduces errors like
```
sage: SR(a).log()
Traceback (most recent call last):
...
TypeError: log() takes exactly one argument (0 given)
```
The question of where and how to fix this might require a discussion.

**Comment by rwst** [comment]
The conversion to `numeric` might not be a problem because `numeric` is not "numeric" in the usual sense. The error comes from finite field elements requiring a base for the log. Try `SR(a).log(2)`. We might want to give them a default base argument (if possible, I'm no algebraist).

**Comment by behackl** [comment]
In principle, the generator `a` itself would be a somewhat intelligent choice of the base, I guess.

Note that I have
```
sage: SR(a).log(2)
Traceback (most recent call last):
...
TypeError: log() takes exactly one argument (0 given)
```

as well as

```
sage: SR(a).log(a)
Traceback (most recent call last):
...
TypeError: log() takes exactly one argument (0 given)
```

However, we might be able to fix this somehow.

In any case, I'm not sure whether I like the following:
```
sage: SR(a).parent()
Symbolic Ring
sage: (SR(a) + 1).parent()
Symbolic Ring
sage: SR(a+1) + SR(0.5)
Traceback (most recent call last):
...
TypeError: unsupported operand parent(s) for '+': 'Finite Field in a of size 3^2' and 'Real Field with 53 bits of precision'
```

**Comment by rwst** [comment]
You get the `TypeError` with `a+0.5` as well, this is nothing from `SR`. The wrapping behaviour is how `SR` is defined. You can get the actual Python object of a numeric (if it is a Python object) via `pyobject`:
```
sage: type(SR(a).pyobject())
<type 'sage.rings.finite_rings.element_givaro.FiniteField_givaroElement'>
```
The `log` change would be in `py_log()` in `src/sage/symbolic/pynac.pyx`. I would suggest however to make any change in concert with all other possible member functions of the finite field element class.

**Comment by rwst** [comment]
Maybe you meant the need for a hold context as in http://trac.sagemath.org/ticket/10035
```
sage: with hold:
sage:     SR(a) + SR(0.5)
a + 0.5

**Comment by behackl** [comment]
I'd rather not touch the behavior of the logarithm for finite field elements, so I have another idea for resolving the doctest failure in #138: as I've written there, we should (like Sympy) only simplify if the base is positive. In theory, this also resolves the problem with the finite field elements, if it wouldn't be for the following behavior:
```
sage: k.<a> = GF(9)
sage: SR(a).is_positive()
True
sage: SR(a+1).is_positive()
True
```
This is unfortunate and should be fixed. Not sure yet why the positive-flag is set in the first place, but I'll investigate.

**Comment by behackl** [comment]
See [trac ticket #20162](http://trac.sagemath.org/ticket/20162).
