### ISSUE TITLE
assume: posint

### ISSUE THREAD

**Issue by rwst** [pynac/pynac#144]
```
sage: assume(x, "integer")
sage: assume(x > 0)
sage: x.is_integer()
False
```
This is because we use `set_domain` in `assume`. This is fine but there is no `posint` domain so one should be created.

**Comment by aaditya-thakkar** [comment]
For both the cases:

`x=SR.var('x',domain='positive')`
`assume(x,'integer')`
`x.is_positive()`
`True`

`x=SR.var('x',domain='integer')`
`assume(x>0)`
`x.is_integer()`
`True`

Output should be true, right?

**Comment by aaditya-thakkar** [comment]
any other case needs to be satisfied?

**Comment by rwst** [comment]
Yes the same with both `assume`, if there is no inconsistency.

**Comment by rwst** [comment]
IOW assuming integer on a complex domain should set integer domain, for now.

**Comment by aaditya-thakkar** [comment]
#153

**Comment by behackl** [comment]
I'm pretty sure this happens with negative integers too.

**Comment by aaditya-thakkar** [comment]
@behackl 
`x=SR.var('x',domain='integer')`
`assume(x<0)`
`x.is_integer()`
`True`

gives true.

**Comment by behackl** [comment]
Yes, because there is no separate `negative` domain that could overrule the `integer` domain. `x.is_negative()` will return `False`.

**Comment by rwst** [comment]
@aaditya-thakkar I have added doctests in pynac/sage. One of them is failing. Can you please improve your changes?
