### ISSUE TITLE
simplify some trig root expressions

### ISSUE THREAD

**Issue by rwst** [pynac/pynac#146]
```
sage: sin(pi/12)
-1/12*sqrt(6)*(sqrt(3) - 3)
sage: bool(sin(pi/12) == sqrt(6)/4 - sqrt(2)/4)
True
sage: bool(cos(pi/12) == sqrt(6)/4 + sqrt(2)/4)
True
sage: cot(pi/12)
-1/(sqrt(3) - 2)
sage: bool(cot(pi/12) == sqrt(3) + 2)
True
```

Check the SymPy source for more such goodies.

**Comment by aaditya-thakkar** [comment]
@rwst I have simplified the expressions with the reference of sympy and wikipedia, I am sending a PR regarding this, have a look at it. It's passing the relevant doctests also(function.pyx, expression.pyx)
