### ISSUE TITLE
missing trig function combinations

### ISSUE THREAD

**Issue by rwst** [pynac/pynac#148]
```
sage: sin(acot(x))
sin(arccot(x))
sage: cos(atan2(y, x))
cos(arctan2(y, x))
sage: cos(acot(x))
cos(arccot(x))
```

**Comment by aaditya-thakkar** [comment]
I have implemented trig function combinations. Suggest me if something needs to be updated. #154

**Comment by rwst** [comment]
When all hyperbolic functions are included (I'm at it) we'll need the same for them.
