### ISSUE TITLE
implement trigonometric symmetry simplifications

### ISSUE THREAD

**Issue by rwst** [pynac/pynac#149]
Example:

```
sage: sin(104*pi/105)
sin(104/105*pi)
```

http://trac.sagemath.org/ticket/20139

**Comment by behackl** [comment]
Concretely, do you think of implementing the reflection at `pi/2`, i.e. if `theta > pi/2`, then simplify `trig_function(theta) = some_sign * trig_function(pi - theta)`?

**Comment by rwst** [comment]
Yes, if there is a smaller nonnegative value reflected take that.

**Comment by aaditya-thakkar** [comment]
@rwst, Can I work on this issue or @behackl  is already working on it?

**Comment by behackl** [comment]
I'm currently busy with other things; the last thing I've started was #165, so go ahead. :-)

**Comment by aaditya-thakkar** [comment]
Sure, Thanks!
