### ISSUE TITLE
Zmod element addition fails

### ISSUE THREAD

**Issue by rwst** [pynac/pynac#166]
There are some doctests (from 18787) that still fail. There is however the question if the expected answers are correct, since I made them up myself and can be wrong on the matter. @behackl what do you think? #77 was the previous ticket on this.
http://trac.sagemath.org/ticket/18787

```
**********************************************************************
File "src/sage/symbolic/expression.pyx", line 2905, in sage.symbolic.expression.Expression._add_
Failed example:
    F*Zmod(7)(1) - G
Expected:
    0
Got:
    x^14 + 6*x^14 + x^7 + 6*x^7
**********************************************************************
File "src/sage/symbolic/expression.pyx", line 2912, in sage.symbolic.expression.Expression._add_
Failed example:
    F*Zmod(7)(1)-G
Expected:
    0
Got:
    x0 + 6*x0 + x14 + 6*x14 + x7 + 6*x7
**********************************************************************
File "src/sage/symbolic/expression.pyx", line 2914, in sage.symbolic.expression.Expression._add_
Failed example:
    F-G
Expected:
    14*x13 + 21*x20 + 7*x6
Got:
    x0 + 6*x0 + 14*x13 + 15*x14 + 6*x14 + 21*x20 + 7*x6 + 8*x7 + 6*x7
**********************************************************************
1 item had failures:
   3 of  38 in sage.symbolic.expression.Expression._add_
```

**Comment by behackl** [comment]
Regarding the first example: the result should definitely be 0, and I don't really see why it actually isn't. If you look at the debugtree you find
```
sage: _._dbgprinttree()
add @0x46417c0, hash=0x0, flags=0x3, nops=4
    power @0x4a3ddd0, hash=0x2eba5635, flags=0xb, nops=2
        x (symbol) @0x3e3ea10, serial=5, hash=0x2eba562e, flags=0xf, domain=0, iflags=0000000000000000
        7 (numeric) @0x4a3dd60, hash=0x0, flags=0x7
    1 (numeric) @0x486be50, hash=0x0, flags=0x7
    -----
    power @0x3eb8c60, hash=0x2eba563c, flags=0xb, nops=2
        x (symbol) @0x3e3ea10, serial=5, hash=0x2eba562e, flags=0xf, domain=0, iflags=0000000000000000
        14 (numeric) @0x432afb0, hash=0x0, flags=0x7
    1 (numeric) @0x48b7900, hash=0x0, flags=0x7
    -----
    mul @0x4b20610, hash=0x477fec92, flags=0x8b, nops=1
        x (symbol) @0x3e3ea10, serial=5, hash=0x2eba562e, flags=0xf, domain=0, iflags=0000000000000000
        7 (numeric) @0x4b898a0, hash=0x0, flags=0x7
        =====
    -1 (numeric) @0x30d9f40, hash=0x0, flags=0x7
    -----
    mul @0x3f28670, hash=0x477fec9b, flags=0x8b, nops=1
        x (symbol) @0x3e3ea10, serial=5, hash=0x2eba562e, flags=0xf, domain=0, iflags=0000000000000000
        14 (numeric) @0x38e7160, hash=0x0, flags=0x7
        =====
    -1 (numeric) @0x30d9f40, hash=0x0, flags=0x7
    =====
```
so actually, the coefficients are already correct, and would only need to be added. Not sure why this doesn't happen for the coefficients with multiples of 7 here; somehow the `Zmod(7)` plays a role here. Note that changing this to, for example, `Zmod(3)`, the addition fails for coefficients with a multiple of `3`:
```
sage: G = sum(Zmod(3)(i+1)*x^i for i in [0..20])
sage: F = sum((i+1)*x^i for i in [0..20])
sage: F * Zmod(3)(1) - G
x^18 + 2*x^18 + x^15 + 2*x^15 + x^12 + 2*x^12 + x^9 + 2*x^9 + x^6 + 2*x^6 + x^3 + 2*x^3
``


The other tests actually fail all from the same reason it would seem.

**Comment by behackl** [comment]
Simpler example:
```
sage: Zmod(3)(1)*x + Zmod(3)(2)*x
2*x + x
```

**Comment by rwst** [comment]
I personally would rather not like to deal with ZZ/nZZ in symbolics. SymPy has no interest in this, either:
```
>>> Mod(1,3)*x+Mod(2,3)*x
3⋅x
>>> Mod(2,3)*x+Mod(2,3)*x
4⋅x
```
Maybe we should even make a point and exclude everything that combines variables with algebraic elements other than the usual numbers. Some functions seem to have useful behaviour for such arguments but variables only lead to trouble.

**Comment by behackl** [comment]
That would be my personal feeling, too. Everything would be much easier if we didn't have to care about these cases with positive characteristic.

If we were to disallow this (very confusing!) kind of arithmetic, then we should definitely consult with sage-devel. This might be very troublesome for users that have code depending on this positive characteristic arithmetic in the symbolic ring.

What would it cost to let
```
sage: Zmod(3)(1)*x - Zmod(3)(1)*x
2*x + x
```
evaluate to `0`? I'm not entirely sure what exactly goes wrong, as not even
```
sage: _.collect(x)
2*x + x
```
seems to have an effect. (I would have expected some sort of evaluation, as
```
sage: pi*x + x
pi*x + x
sage: _.collect(x)
(pi + 1)*x
```
also groups the coefficients together.)

**Comment by behackl** [comment]
This is even more disturbing:
```
sage: Zmod(7)(6)*x + x
0
sage: Zmod(7)(6)*x + Zmod(7)(1)*x
6*x + x
```

**Comment by rwst** [comment]
Actually, it seems possible to me to resolve all such issues by implementing #2 because Singular can handle pos.char. rings and is well tested. It would also be a door to more sophisticated things like simplification.

**Comment by rwst** [comment]
The last comment was nonsense, and encouraging people to use dedicate rings by implementing https://trac.sagemath.org/ticket/21391 seems the better idea.
