### ISSUE TITLE
giac not detected if compiled with GCC5 ABI

### ISSUE THREAD

**Issue by nqn76** [pynac/pynac#181]
If giac is compiled with the new GCC 5 ABI, it provides the function _ZN4giac7versionB5cxx11Ev instead of _ZN4giac7versionEv so the configure test fails.

**Comment by rwst** [comment]
Is that a Giac system installation or did you install Giac via `sage -i giac`? (It makes no difference for this issue but I like to know if this can happen with a Sage installation)

**Comment by rwst** [comment]
Fixed in master. Thanks for reporting.

**Comment by nqn76** [comment]
This is with system giac, but I suppose the same would happen with the sage one if sage was compiled with GCC 5.
Thanks for the fix
