### ISSUE TITLE
sage doctest fails when pynac-0.6.8 is compiled with giac 1.2.2_69

### ISSUE THREAD

**Issue by kiwifb** [pynac/pynac#185]
From sage-on-gentoo. I am following Volker's branch where pynac-0.6.8 has been merged. One of the doctest (only one) fails when pynac has been compiled to use giac (currently at 1.2.2_69 which would the one we want to upgrade to in sage).

```
fbissey@QCD-nzi3 ~ $ sage -t --long /usr/lib64/python2.7/site-packages/sage/symbolic/expression.pyx
too many failed tests, not using stored timings
Running doctests with ID 2016-08-07-12-21-47-be42b415.
Using --optional=optional,sage
Doctesting 1 file.
sage -t --long /usr/lib64/python2.7/site-packages/sage/symbolic/expression.pyx
**********************************************************************
File "/usr/lib64/python2.7/site-packages/sage/symbolic/expression.pyx", line 8398, in sage.symbolic.expression.Expression.normalize
Failed example:
    ((x - 2*y)^4/(x^2 - 4*y^2)^2).normalize()
Expected:
    (x - 2*y)^2/(x + 2*y)^2
Got:
    (x^2 - 4*x*y + 4*y^2)/(x^2 + 4*x*y + 4*y^2)
**********************************************************************
1 item had failures:
   1 of  12 in sage.symbolic.expression.Expression.normalize
    [2630 tests, 1 failure, 39.86 s]
----------------------------------------------------------------------
sage -t --long /usr/lib64/python2.7/site-packages/sage/symbolic/expression.pyx  # 1 doctest failed
```

I will check if a newer giac solve the problem a bit later.

**Comment by kiwifb** [comment]
Doctest still failing with giac 1.2.2-75.

**Comment by rwst** [comment]
That doctest was introduced by https://trac.sagemath.org/ticket/19775, i.e. later than the introduction of optional giac support. I don't think we can guarantee absence of such optional failures after the fact. As to the problem itself, the pynac+giac GCD is done by converting to giac multivar poly and execute their GCD which expands factorisations. This is an acceptable ticket but I'm unclear atm how to resolve it.

**Comment by rwst** [comment]
One possibility is to use Giac's expressions instead of its polynomials: this would require a full expression conversion interface like those that Sage has with Maxima or SymPy; after all the effort both still are incomplete however.

The other possibility is to preprocess more before handing to the poly GCD, like substituting whole parentheses.

**Comment by rwst** [comment]
The doctest in question recently was marked in Sage as "known bug" so this is no longer pressing.

**Comment by rwst** [comment]
Actually fixed via 673944ed03ac452b166e63f7d30774fc233f97e4

**Comment by kiwifb** [comment]
I will test ASAP.

**Comment by kiwifb** [comment]
Cannot actually test until `pynac` in sage is updated unless I adopt that particular commit. I actually spend the last few hours in `giac`'s configure.in and makefiles, I actually feel I visited some sewers.

**Comment by kiwifb** [comment]
Seems all good now.
