### ISSUE TITLE
Support for special printing options to print derivatives better

### ISSUE THREAD

**Issue by nbruin** [pynac/pynac#187]
A thing that has been bugging people using sage for a while is that an expression like

D\[0\](f)(x,y)

could be printed as diff(f(x,y),x), which a lot of people would consider much more readable. GiNaC does expose hooks to print functions in a special way, see for instance http://www.ginac.de/tutorial/#Print-methods-for-functions . However, special print methods are not exposed at all in PyNaC (I think there is a comment to that effect in PyNaC somewhere). 

It would really help if we could expose these hooks at least to the extent that we can implement a smarter printer for "FDerivative" applications. For instance, if we could just dispatch to, say, "operator_application_repr(self, \*arguments)" and "operator_application_latex(self,\*arguments)" if those methods exist on the "operator" object, it would be very straightforward to generate much more user-friendly string representations for derivatives.

**Comment by kcrisman** [comment]
A thing that has been bugging people using sage for a while is that an
> expression like
>
> D0 <http://f>(x,y)
>
> could be printed as diff(f(x,y),x), which a lot of people would consider
> much more readable.
>

+1 for this being possible.

**Comment by billpage** [comment]
+1

**Comment by nbruin** [comment]
Browsing a little through the code: it seems we would already be able to do this if just the file
fderivative.cpp
gets adjusted (although it seems a little bit of an issue that at fderivative::do_print doesn't have an "args" argument anymore, which is part of the print function signatures that go into REGISTER_FUNCTION in GiNaC. I would expect we can drill down to a level where that parameter is available again?)

**Comment by billpage** [comment]
It seems like there is already a special kind of hook for LaTeX
https://github.com/pynac/pynac/blob/master/ginac/fderivative.cpp#L112
Maybe something like this is easier?

**Comment by nbruin** [comment]
Excellent find! The relevant routine is defined here:

https://github.com/sagemathinc/smc-sage/blob/f524d58c3db07856140f5557aa57cfa21a5895b3/src/sage/symbolic/pynac.pyx#L583

so it looks like we should be able to patch this inside sage already! No change to PyNaC would be required. I'll leave this issue open for now, until we see on the corresponding sage trac ticket if we can indeed solve this issue on the sage side.
