### ISSUE TITLE
infinite recursion

### ISSUE THREAD

**Issue by rwst** [pynac/pynac#19]
http://trac.sagemath.org/ticket/18210

**Comment by behackl** [comment]
Is this infinite recursion still a Pynac-issue? After all, according to the ticket the problem went away with 6.7.beta0 or 6.7.beta1 -- and this is still with the same version of Pynac as we had in 6.6 (and 6.5.beta1).

**Comment by rwst** [comment]
It is because Pynac should not do it, regardless of what it gets fed by Sage.

**Comment by behackl** [comment]
My question was formulated poorly, sorry. Of course the infinite recursion should not happen in any case -- but the priority for investigating this is probably different.

**Comment by rwst** [comment]
Yes, I removed it from the milestone. But milestones are not set in stone, anyway 8)

**Comment by rwst** [comment]
OK, I agree to close this, mostly because I cannot reproduce it any more.
