### ISSUE TITLE
Define gegenbauer(n,a,x) when 'a' is not numeric

### ISSUE THREAD

**Issue by crmafra** [pynac/pynac#197]
I recently started using sage and I noticed that the gegenbauer polynomial 
gegenbauer(n,a,x) requires both 'n' and 'a' to be numeric in order to return its
symbolic expression.

But the definition makes sense for a symbolic 'a' too. For example, 

gegenbauer(2,a,x) = 2*a^2*x^2 + 2*a*x^2 - a

After some investigation in the source code, I arrived at pynac, so here I am.

Is it possible to lift the restriction of 'a' being numeric in the definition of
gegenb_eval() in the file inifcns_orthopoly.cpp?

At first I tried to fix this myself but I am not very familiar with C++.

**Comment by crmafra** [comment]
I wrote a patch for this, see attached file.

I've just tested it with sage and now I get the expected output:

sage: var('a')
sage: gegenbauer(2,a,x).expand()
2*a^2*x^2 + 2*a*x^2 - a

The patch is probably too naive as I used the recursive definition instead of the open-coded
formula (because I couldn't follow what was going on). But hey, I am happy still.
[0001-Support-gegenbauer-n-a-x-with-non-numeric-a.txt](https://github.com/pynac/pynac/files/504694/0001-Support-gegenbauer-n-a-x-with-non-numeric-a.txt)

**Comment by rwst** [comment]
Hello, thanks for looking at this. As to your patch it will not do to delete the fast numeric code, but we can add the recurrence as a special case. I'll acknowledge your authorship. See ad6968a9f0bc9f23fb3fa7649590d7de75bdb857

However at `n>>20` it becomes unusable so we should find a holonomic formula for it (there is one for sure).

**Comment by rwst** [comment]
Closed with ad6968a9f0bc9f23fb3fa7649590d7de75bdb857
