### ISSUE TITLE
find fast formula for gegenbauer(n,a,x) when 'a' is not numeric

### ISSUE THREAD

**Issue by rwst** [pynac/pynac#198]
The current recurrence for non-numeric `a` gets unusable with `n>>20`.

**Comment by rwst** [comment]
@crmafra submitted the following patch:
```
diff --git a/ginac/inifcns_orthopoly.cpp b/ginac/inifcns_orthopoly.cpp
index 5418357..0957ce9 100644
--- a/ginac/inifcns_orthopoly.cpp
+++ b/ginac/inifcns_orthopoly.cpp
@@ -129,9 +129,32 @@ static ex gegenb_eval(const ex& n, const ex &a, const ex& x)
                return _ex2 * a * x;
 
        if (not is_exactly_a<numeric>(a)) {
-                return _ex1 * 1/numn*(2*x*(numn + a - 1)*gegenb_eval(numn-1,a,x)
-                       - (numn + 2*a - 2)*gegenb_eval(numn-2,a,x));
-        }
+               ex p = _ex1;
+               ex sum = _ex0;
+               ex sign = _ex1;
+               ex aa = _ex1;
+               unsigned long nn = numn.to_long();
+
+               for (unsigned long k=0; k<=nn/2; k++) {
+                       aa = a;
+                       p = 1;
+                       // rising factorial (a)_{n-k}
+                       for (unsigned long i=0; i<nn-k; i++) {
+                               p *= aa;
+                               aa = aa + 1;
+                       }
+
+                       if ((k%2) != 0)
+                               sign = - 1;
+                       else
+                               sign = 1;
+
+                       p /= numeric(k).factorial();
+                       p /= numeric(nn-2*k).factorial();
+                       sum += pow(2*x, nn-2*k) * p * sign;
+               }
+               return sum;
+       }
 
         numeric numa = ex_to<numeric>(a);
         if (not numa.info(info_flags::rational) or numa < 0)
```
This looks good and seems correct. The output with all the rising factorials of `a` should be replaced by `gamma(a+b)/gamma(a)` as long as there is no fully symbolic `rising_factorial()` in Sage.

**Comment by crmafra** [comment]
Ralf, I don't understand the comment about the rising_factorial(). Do you want that the output of
gegenbauer(n,a,x) be written in terms of gamma()'s? Mathematica doesn't do that and I agree with it.

I was actually wondering if there is a more efficient way to handle the 'sign' in my patch by simply having a statement sign *= - sign; in the beginning of the for(k=0,...) loop. It would save us some lines and it's probably a bit more efficient.

**Comment by crmafra** [comment]
I prepared a patch for the 'sign' idea on top of the patch above. It's attached.
[patch.txt](https://github.com/pynac/pynac/files/506298/patch.txt)

**Comment by rwst** [comment]
Thanks. I've put it all into ddfa0020ac7263d898732ea0e95e84bbebe20f10
