### ISSUE TITLE
0^0 = 1 (not a ValueError)

### ISSUE THREAD

**Issue by rwst** [pynac/pynac#20]
See http://trac.sagemath.org/ticket/18088
Apparently Ginac says zero to the zero is undefined but most of the rest of Sage (in accordance with IEEE) says it is one:
```
sage: SR(0)^SR(0)
ValueError: power::eval(): pow(0,0) is undefined
```

**Comment by kcrisman** [comment]
Is this worth reporting upstream, or do you think they would complain/reject it?

**Comment by rwst** [comment]
They would probably ignore it (I already tried to contribute to GiNaC 10 years ago).

**Comment by kcrisman** [comment]
Interessant.
