### ISSUE TITLE
extern installation does not compile without system-installed Flint

### ISSUE THREAD

**Issue by rwst** [pynac/pynac#206]
Would like to easily use the Sage installation of Flint, even with manual compile.

**Comment by rwst** [comment]
Just set `CXXFLAGS="-I$SAGE_LOCAL/include"` and `./configure`.

**Comment by rwst** [comment]
Since #209 this is better: `./configure CFLAGS="-I$SAGE_LOCAL/include"`

**Comment by kiwifb** [comment]
Is setting `CFLAGS` really necessary? `sage-env` sets up `CPATH` so that shouldn't be needed, unless you are not doing it from a sage shell - and really if you want the stuff installed by sage, you should get to a sage shell first.

**Comment by rwst** [comment]
I think you misunderstand. My problem is compiling outside Sage (to test compilation works) but using the Sage flint headers.

**Comment by kiwifb** [comment]
I misunderstood all right. What you really need in that case is a `--with-flint=DIR` switch. After merging my request you will need `./configure CFLAGS="-I$SAGE_LOCAL/include" LDFLAGS="-L$SAGE_LOCAL/lib"` because linking is also tested.

**Comment by rwst** [comment]
I'm still not sure if doing a configure with different flags will affect a later `make dist` (which produces the tarball for distribution), but I'm probably overly cautious here.
