### ISSUE TITLE
coeff() problem with fraction as argument

### ISSUE THREAD

**Issue by rwst** [pynac/pynac#216]
https://trac.sagemath.org/ticket/19996
```
sage: (x^(1/2)).coefficient(x, 1/3)
sqrt(x)    # should be 0
sage: (x^(1/2)).coefficient(y, QQ(1)/3)
sqrt(x)    # should be 0
sage: (x^(1/2)).coefficient(y, QQ(4)/3)
0
```

**Comment by Sravani-Kalangi** [comment]
What exactly is the expected/desired output?

**Comment by rwst** [comment]
They should all be zero, just like they are with:
```
sage: (x^(1/2)).coefficient(x^(1/3))
sage: (x^(1/2)).coefficient(y^(1/3))
sage: (x^(1/2)).coefficient(y^(4/3))
```

**Comment by Sravani-Kalangi** [comment]
Can it be done this way:
         If n is a fraction then we find the coefficients() list and check in it if there is no matching value found then we return a zero output

**Comment by Sravani-Kalangi** [comment]
using a logic something like this:
sage: f=x^(1/2)+17*x^2
sage: f.coefficients()
[[1, 1/2], [17, 2]]
sage: any(e[1] == (QQ(4)/3) for e in f.coefficients())
False
sage: any(e[1] == (QQ(1)/3) for e in f.coefficients())
False
sage: any(e[1] == (1/3) for e in f.coefficients())
False
sage: any(e[1] == 2 for e in f.coefficients())
True
sage: any(e[1] == (1/2) for e in f.coefficients())
True
sage: any(e[1] == (3/2) for e in f.coefficients())
False

where if we it is evaluated false we can return zero

**Comment by rwst** [comment]
What you write is Python. Pynac is C++. Please put any working code in a pull request.
