### ISSUE TITLE
giac support is broken in 0.7.3

### ISSUE THREAD

**Issue by antonio-rojas** [pynac/pynac#223]
ImportError: /usr/lib/libpynac.so.9: undefined symbol: _ZN5GiNaC9resultantERKNS_2exES2_S2_

Introduced in commit a91c27d

**Comment by antonio-rojas** [comment]
./bootstrap
  ./configure --prefix=/usr
  make
  make install

Using the tarball from github

**Comment by rwst** [comment]
Please in general use Pynac only with Sage. You only need to install Pynac manually if you do Pynac development and if so, then please use the procedure in https://github.com/pynac/pynac/wiki/Setting-up-a-development-environment. If you just want to use pynac-0.7.3 now you can use the Sage branch at https://trac.sagemath.org/ticket/22136, copy the Pynac tarball to your upstream directory, and do `make`.

However, it's good to see that people indeed try `make install` so we will try to output some info at the attempt. I'll change this ticket to reflect this.

**Comment by antonio-rojas** [comment]
So what is the recommended way to install it for distro packaging?

**Comment by rwst** [comment]
Distro-packaging is not supported with Sage. Where did you hear that it is?

**Comment by rwst** [comment]
That's it. Pynac and other Sage packages have meta-info in the spkg files, and the configure options there should be copied if you do this. Here is the current `build/pkgs/pynac/spkg-install`:
```
#!/usr/bin/env bash
###########################################
## pynac
###########################################


# The makefile system sets this variable, which screws up autoconf...
unset PYTHON

if [ "$SAGE_LOCAL" = "" ]; then
    echo "SAGE_LOCAL undefined ... exiting";
    echo "Maybe run 'sage -sh'?"
    exit 1
fi

CXXFLAGS="-O2 -g"

if [ "$SAGE64" = "yes" ]; then
    echo "Building a 64-bit version of pynac"
    CXXFLAGS="-m64 $CXXFLAGS"; export CXXFLAGS
    LDFLAGS="-m64 $LDFLAGS"; export LDFLAGS
    CC="$CC -m64" ; export CC
    CXX="$CXX -m64" ; export CXX
fi

WORKDIR=${PWD}/src
PYNACDIR=${WORKDIR}

patch()
{
    true
}

build_pynac()
{
    cd ${PYNACDIR}
    PKG_CONFIG_PATH=${SAGE_LOCAL}/lib/pkgconfig; export PKG_CONFIG_PATH
    ./configure --disable-static --prefix=${SAGE_LOCAL} --with-giac=no --libdir="$SAGE_LOCAL/lib"
    $MAKE
    if [ $? -ne 0 ]; then
        echo "Error building pynac."
        exit 1
    fi
    cd ${WORKDIR}
}

install_pynac()
{
    rm ${SAGE_LOCAL}/lib/*ginac*
    rm ${SAGE_LOCAL}/lib/*pynac*
    rm -rf ${SAGE_LOCAL}/include/ginac
    rm -rf ${SAGE_LOCAL}/include/pynac
    cd ${PYNACDIR}
    $MAKE install
    if [ $? -ne 0 ]; then
        echo "Error installing pynac."
        exit 1
    fi
    cd ${WORKDIR}
}

clean_pynac()
{
    true
}

patch


cd src

echo "Starting build..."
echo "Running build_pynac..."
build_pynac
echo "Done build_pynac."

echo "Installing pynac..."
install_pynac
echo "Done installing pynac."
```

**Comment by antonio-rojas** [comment]
ok - then the issue is that giac support is broken in 0.7.3 - resultant is being called unconditionally in sum.cpp but only defined in mpoly-ginac.cpp if PYNAC_HAVE_LIBGIAC is not defined.

**Comment by rwst** [comment]
Fixed in master.
