### ISSUE TITLE
to_gamma() sporadic errors

### ISSUE THREAD

**Issue by rwst** [pynac/pynac#231]
The doctest
```
            sage: m,n = var('m n', domain='integer')
            sage: binomial(m,n).to_gamma()
            gamma(m + 1)/(gamma(m - n + 1)*gamma(n + 1))
```
sometimes fails on some machines, i.e. it doesn't reach the line
https://github.com/pynac/pynac/blob/master/ginac/sum.cpp#L180

More info is needed.

**Comment by jdemeyer** [comment]
The problem is also in Pynac-0.7.5.

What could I do to debug this?

**Comment by rwst** [comment]
Myself I would trace with gdb, setting a breakpoint at line 165 and looking why it does not get to line 180. Alternatively you can insert printing markers. If the function is reached there are just three branches that can lead to a bailout before the correct branch is reached.

**Comment by rwst** [comment]
Or you can give me an account on that machine.

**Comment by rwst** [comment]
@jdemeyer However, I have the suspicion that `ex_to<function>(binomial(m,n)).get_serial()` is for some reason different than `binomial_SERIAL::serial`.

**Comment by jdemeyer** [comment]
> I have the suspicion that ex_to<function>(binomial(m,n)).get_serial() is for some reason different than binomial_SERIAL::serial.

That's not the issue. The serials are 1 in both cases.

The problem seems to be with `static std::unordered_map<unsigned int,tgfun_t*> funcmap`: it contains only one element, namely the first one (factorial). I added this:
```
std::cout << "funcmap.size() = " << funcmap.size() << std::endl;
```
and it prints
```
funcmap.size() = 1
```

So either there is a bug in my stdc++ library, or you are misusing `std::unordered_map`.

**Comment by rwst** [comment]
https://github.com/pynac/pynac/blob/master/ginac/useries.cpp#L224
is another example where this construct works.

**Comment by rwst** [comment]
The output is different here,
```
funcmap.size() = 5
```

**Comment by rwst** [comment]
Maybe it's not the std lib, maybe all, serials are 1 for some reason?

**Comment by jdemeyer** [comment]
> Maybe it's not the std lib, maybe all serials are 1 for some reason?

No:
```
factorial_SERIAL::serial = 0
tgamma_SERIAL::serial = 8
binomial_SERIAL::serial = 1
rising_factorial_SERIAL::serial = 2
falling_factorial_SERIAL::serial = 3
```

I can reproduce the problem both with GCC 4.9.3 and GCC 5.4.0, so I don't know what else to try...

**Comment by jdemeyer** [comment]
> https://github.com/pynac/pynac/blob/master/ginac/useries.cpp#L224
> is another example where this construct works.

Is that doctested in Sage?

**Comment by rwst** [comment]
>> https://github.com/pynac/pynac/blob/master/ginac/useries.cpp#L224
>> is another example where this construct works.
>
> Is that doctested in Sage?

Yes, in both `symbolic/series.pyx` and `tests/symbolic-series.py`.

**Comment by jdemeyer** [comment]
Progress! This fixes it:
```diff
diff --git a/ginac/sum.cpp b/ginac/sum.cpp
index b65454d..3411ce8 100644
--- a/ginac/sum.cpp
+++ b/ginac/sum.cpp
@@ -106,11 +106,11 @@ static ex falling_factorial_to_gamma(const function& f)
 
 using tgfun_t = decltype(gamma_to_gamma);
 static std::unordered_map<unsigned int,tgfun_t*> funcmap {{
-        {factorial_SERIAL::serial, &factorial_to_gamma},
-        {tgamma_SERIAL::serial, &gamma_to_gamma},
-        {binomial_SERIAL::serial, &binomial_to_gamma},
-        {rising_factorial_SERIAL::serial, &rising_factorial_to_gamma},
-        {falling_factorial_SERIAL::serial, &falling_factorial_to_gamma},
+        {0, &factorial_to_gamma},
+        {8, &gamma_to_gamma},
+        {1, &binomial_to_gamma},
+        {2, &rising_factorial_to_gamma},
+        {3, &falling_factorial_to_gamma},
 }};
 
 static bool has_suitable_form(ex the_ex)
```

Most likely, the map is initialized **before** the serials are computed. So all serials are zero when the map is constructed.

**Comment by jdemeyer** [comment]
See https://isocpp.org/wiki/faq/ctors#static-init-order

**Comment by rwst** [comment]
Please try master.

**Comment by jdemeyer** [comment]
Works for me!
