### ISSUE TITLE
is_real(zeta(real)) is true

### ISSUE THREAD

**Issue by rwst** [pynac/pynac#240]
Any more functions?

**Comment by kcrisman** [comment]
(Although there is that pesky pole - does that still count as real?)

**Comment by rwst** [comment]
Consistency with:
```
sage: zeta(1)
Infinity
sage: _.is_real()
True
```
would dictate so although unsigned `oo` is often equalled with complex `oo`.

**Comment by kcrisman** [comment]
Got it!
