### ISSUE TITLE
fix py_crational and/or its usage

### ISSUE THREAD

**Issue by rwst** [pynac/pynac#253]
We rely on the Python functions but they are buggy:
```
sage: from sage.libs.pynac.pynac import py_is_crational_for_doctest
sage: py_is_crational_for_doctest(1)
sage: py_is_crational_for_doctest(2*I)
False
sage: py_is_cinteger_for_doctest(2*I)
False
```

**Comment by mforets** [comment]
don't know if this is related (i'm in pynac master `pynac-0.7.8.tar.bz2`):

```
sage: x = var('x', domain='real') 
sage: conjugate(x+I)
x + I
```
reported recently in [ask sage: a problem with variables in real domains](https://ask.sagemath.org/question/37766/a-problem-with-variables-in-real-domains/)
