### ISSUE TITLE
numbers.cpp should not depend on precise Sage modules

### ISSUE THREAD

**Issue by videlec** [pynac/pynac#296]
The explicit references to `sage.rings.real_mpfr` and `sage.rings.real_field` in pynac make it impossible to relocate these modules in Sage without patching (see [#24483](https://trac.sagemath.org/ticket/24483)). It would be much simpler with one of the two solutions:
- import them from `sage.rings.all` which is not likely to change in the near future
- use a file `sage.libs.pynac.ring_declarations`

**Comment by rwst** [comment]
Thanks. We will use `sage.rings.all`.
