### ISSUE TITLE
clang-check cstddef error

### ISSUE THREAD

**Issue by rwst** [pynac/pynac#305]
```
/home/ralf/sage/pynac/ginac/basic.h:26:10: fatal error: 'cstddef' file not found
#include <cstddef> // for size_t
```
Maybe this started with the new `ax_cxx_compile_stdcxx.m4`?

**Comment by rwst** [comment]
@kiwifb Maybe the clang ticket will give this error. I'm investigating.

**Comment by rwst** [comment]
Ok that is a misconfiguration of clang-check but when fixed I get the more serious
```
In file included from /home/ralf/sage/pynac/ginac/constant.cpp:23:
In file included from /home/ralf/sage/local/include/python2.7/Python.h:42:
In file included from /home/ralf/sage/local/include/c++/7.2.0/stdlib.h:36:
/home/ralf/sage/local/include/c++/7.2.0/cstdlib:41:10: fatal error: 
      'bits/c++config.h' file not found
#include <bits/c++config.h>
```

**Comment by kiwifb** [comment]
How do you get that? This is a g++ internal header.

**Comment by rwst** [comment]
> How do you get that?
By giving the command `clang-check ginac/constant.cpp -p compile_commands.json`.
Probably by having a wrong include path somewhere, maybe still my clang-check configuration.
The `cstddef` is included from `basic.h` but I noticed I don't need it any longer.

**Comment by rwst** [comment]
Confirm a clang-check misconfiguration that probably showed after a new `AX_CXX_COMPILE_STDCXX` macro was installed.
