### ISSUE TITLE
gcd() tries to compare potentially uncomparable numbers

### ISSUE THREAD

**Issue by jdemeyer** [pynac/pynac#338]
Executing this in Sage
```
alg = SR(QQbar(sqrt(2) + I*sqrt(3))); gcd(alg - alg*x, x^2 - 1)
```
uses Pynac, which goes through the following code sequence:

1. `gcdpoly` is entered: https://github.com/pynac/pynac/blob/798a8b7344bc688e27fc8e61cfa38076d912311f/ginac/mpoly-singular.cpp#L351
2. `to_canonical` is called on the inputs: https://github.com/pynac/pynac/blob/798a8b7344bc688e27fc8e61cfa38076d912311f/ginac/mpoly-singular.cpp#L542
3. `num2canonical` is called: https://github.com/pynac/pynac/blob/798a8b7344bc688e27fc8e61cfa38076d912311f/ginac/mpoly-singular.cpp#L214
4. `replace_with_symbol(I, map, revmap)` is called: https://github.com/pynac/pynac/blob/798a8b7344bc688e27fc8e61cfa38076d912311f/ginac/mpoly-singular.cpp#L106
5. This tries to find `I` in `map`: https://github.com/pynac/pynac/blob/798a8b7344bc688e27fc8e61cfa38076d912311f/ginac/mpoly-singular.cpp#L64
6. Since `std::map` compares its arguments, this eventually calls `alg < I` in Python.

This is a problem because on Python 3 one cannot compare arbitrary Python objects. One should not assume that there is always a meaningful ordering (comparing for equality is fine though). And even if there is an ordering, it's best not to assume that it's transitive.

**Comment by jdemeyer** [comment]
@rwst Do you have any plans to fix this? Would it be possible to use a different data structure instead of `std::map`?

**Comment by rwst** [comment]
`std::map` can be initialized with a different compare function:
```
template<
    class Key,
    class T,
    class Compare = std::less<Key>,
    class Allocator = std::allocator<std::pair<const Key, T> >
> class map;
```
See https://en.cppreference.com/w/cpp/container/map

We're using 
https://github.com/pynac/pynac/blob/5a2bbdc7d37d9d83bcd9da8bbb8ba9db6e7ba136/ginac/basic.h#L74
`ex_is_less` is here:
https://github.com/pynac/pynac/blob/5a2bbdc7d37d9d83bcd9da8bbb8ba9db6e7ba136/ginac/ex.h#L676-L678
I'd suggest defining a comparator that checks if the `ex` is numeric and a `PYOBJECT` by using:
https://github.com/pynac/pynac/blob/5a2bbdc7d37d9d83bcd9da8bbb8ba9db6e7ba136/ginac/numeric.h#L510-L5140

**Comment by rwst** [comment]
Or even better change `numeric::compare_same_type`:
https://github.com/pynac/pynac/blob/5a2bbdc7d37d9d83bcd9da8bbb8ba9db6e7ba136/ginac/numeric.cpp#L630-L644

**Comment by jdemeyer** [comment]
The problem is that you should not assume that `x < y` makes sense when `x` and `y` are Python objects. So we really want a solution that does not rely on `<` at all.

**Comment by jdemeyer** [comment]
Maybe `std::unordered_map`?

**Comment by rwst** [comment]
Just found it myaself, yes. It's also used already in Pynac.

**Comment by rwst** [comment]
Equivalently to the code above there is `numeric::is_equal()` calling `numeric::operator==()` which has:
https://github.com/pynac/pynac/blob/5a2bbdc7d37d9d83bcd9da8bbb8ba9db6e7ba136/ginac/numeric.cpp#L2942-L2946

**Comment by rwst** [comment]
This could be sped up by checking the `numeric`'s `hash` field before calling `py_is_equal`.

**Comment by jdemeyer** [comment]
Do you plan to fix this or should I provide a pull request?

**Comment by rwst** [comment]
Please provide a PR.

**Comment by rwst** [comment]
As I have not a Sage installation with Py3 I simply assume you tested it.

**Comment by jdemeyer** [comment]
I did not test with Python 3 but I did test with https://trac.sagemath.org/ticket/22029
