### ISSUE TITLE
The pynac.pc.in file seems incorrect

### ISSUE THREAD

**Issue by SnarkBoojum** [pynac/pynac#343]
According to [the official documentation](https://wiki.openmandriva.org/en/Overlinking_issues_in_packaging#pkgconfig_issues), the .pc file shouldn't list flint, gmp and giac in Libs but in Libs.private.

I'm testing a patch -- I'll attach it here if it looks ok.

**Comment by SnarkBoojum** [comment]
Ok, that looks nice 
[pkgconfig.patch.txt](https://github.com/pynac/pynac/files/3170443/pkgconfig.patch.txt)

**Comment by rwst** [comment]
OK, I committed for you. Thanks.
