### ISSUE TITLE
No soname bump?

### ISSUE THREAD

**Issue by SnarkBoojum** [pynac/pynac#346]
For the transition off Python 2 in Debian, I'd like to move pynac to Python 3 - unfortunately, that gives a library with the same soname, but still incompatible.

So this ticket is mostly to ask : will you soon release a version with a natural soname bump which will allow me to transition smoothly, or should I try to hack something on my side in Debian?

**Comment by rwst** [comment]
Please submit a pull request.

Best,

**Comment by SnarkBoojum** [comment]
We found another way than a soname bump for the time being, but if there's a good reason for a natural soname bump on your side, we'll use it to clean our packaging. Thanks!
