### ISSUE TITLE
rpm target should be PHONY

### ISSUE THREAD

**Issue by orlitzky** [pynac/pynac#350]
In the `Makefile.am`, there's a target...

```
# Rule to build RPM distribution package
rpm: $(PACKAGE)-$(VERSION).tar.gz
	rpmbuild -ta --clean $(PACKAGE)-$(VERSION).tar.gz
```

that tries to build a file literally called `rpm`. Since the rpmbuild command doesn't do that, this happens to work, but would fail if e.g. someone created a directory named `rpm` in the project root. There's a one-line fix for this: [make it a PHONY target.](https://www.gnu.org/savannah-checkouts/gnu/make/manual/html_node/Phony-Targets.html)

**Comment by fchapoton** [comment]
done
