### ISSUE TITLE
Error is thrown in numeric::power with negative rational exponent and numerator greater than 32 bits

### ISSUE THREAD

**Issue by bmlivin** [pynac/pynac#356]
This is based on [Sage trac #29156](https://trac.sagemath.org/ticket/29156). I'm going to summarize what I said over there:

In `numeric::power`, if the exponent is negative and rational and has a numerator greater than 32 bits, the method `to_long` is called. This method checks whether the numerator is greater than 32 bits or not, and if so, throws an error. I do not think an error should be thrown in this situation since it wouldn't be if the numerator was one bit smaller or if the exponent was positive. However, I'm not sure what the best thing to do in this situation is either.

**Comment by dimpase** [comment]
fixed by #358
