### ISSUE TITLE
Repackage pynac as a pip-installable package

### ISSUE THREAD

**Issue by mkoeppe** [pynac/pynac#361]
Pynac has a compile-time dependency on the Python library but is not installed using Python package infrastructure. This is problematic because Python users cannot install it using standard Python tools - for example for testing different Python versions.

See https://trac.sagemath.org/ticket/30534 for more details.

**Comment by dimpase** [comment]
OK, GitHub Actions are running on the repo, again. Took them a while to fix.

**Comment by mkoeppe** [comment]
At https://trac.sagemath.org/ticket/32386 we are using a different approach now to solve the same issue.
