### ISSUE TITLE
Adapt to float factorial deprecation in Python 3.9

### ISSUE THREAD

**Issue by slel** [pynac/pynac#364]
Python 3.9 deprecates using `math.factorial` with floats with integral values.

- ​https://docs.python.org/3.9/library/math.html#math.factorial

  > Deprecated since version 3.9:
  > Accepting floats with integral values (like 5.0) is deprecated.

This gives a doctest failure in Sage 9.2.rc0 with Python 3.9.0:
```
File "src/sage/functions/other.py", line 1629, in sage.functions.other.Function_factorial._eval_
Failed example:
    factorial(float(3.2))        # abs tol 1e-14
      File "<doctest sage.functions.other.Function_factorial._eval_[8]>", line 1, in <module>
        factorial(float(RealNumber('3.2')))        # abs tol 1e-14
      File "/Users/mkoeppe/s/sage/sage-rebasing/worktree-py39/local/lib/python3.9/warnings.py", line 109, in _showwarnmsg
        sw(msg.message, msg.category, msg.filename, msg.lineno,
    :
    DeprecationWarning: Using factorial() with floats is deprecated
    7.756689535793181
```

First discussed in [Sage Trac ticket 30184 (Support Python 3.9)](https://trac.sagemath.org/ticket/30184)
(comments 25, 33, 40, 41, 42, 43), this is the object of
[Sage Trac ticket 30764: Adapt to float factorial deprecation in Python 3.9](https://trac.sagemath.org/ticket/30764)
where it was analysed that `factorial(float(3.2))`
calls the `__call__` method for `Function` in 
`symbolic/function.pyx`, which in this case executes the code:
```
        if not symbolic_input and is_a_numeric(res):
            return py_object_from_numeric(res)
```
where `py_object_from_numeric` comes from `libs/pynac/pynac.pxd`.

**Comment by fchapoton** [comment]
maybe the relevant code is here:

https://github.com/pynac/pynac/blob/master/ginac/numeric.cpp#L3995

**Comment by fchapoton** [comment]
should probably be closed as invalid, as it was fixed inside sage and is a python problem

**Comment by slel** [comment]
Ok.
