### ISSUE TITLE
The configure script doesn't check the C++11 support, and doesn't enable it

### ISSUE THREAD

**Issue by SnarkBoojum** [pynac/pynac#61]
I suggest to add the following [autoconf script](https://www.gnu.org/software/autoconf-archive/ax_cxx_compile_stdcxx_11.html) to m4/ and call it from configure.ac : that way if the C++ compiler doesn't support C++11, you'll get an error, and if it needs an additional switch to enable support, the switch will be added.

Snark on #sagemath

**Comment by rwst** [comment]
See https://github.com/pynac/pynac/commit/ffbb0809772dd28496962bd0d629e3d606db2440

**Comment by SnarkBoojum** [comment]
Where does that commit add the required file to m4/ ?

**Comment by rwst** [comment]
Indeed, thanks!
