### ISSUE TITLE
remove unused files part 2

### ISSUE THREAD

**Issue by rwst** [pynac/pynac#63]
As discussed [in this Wiki page](https://github.com/pynac/pynac/wiki/Which-part-of-Pynac-gets-actually-used%3F) these (by Sage) unused files are part of a nexus that potentially slows down Pynac operation, and could be deleted after adaptation:

```
idx.h idx.cpp varidx.h varidx.cpp indexed.h indexed.cpp
clifford.h clifford.cpp color.h color.cpp integral.h integral.cpp
ncmul.h ncmul.cpp tensor.h tensor.cpp symmetry.h symmetry.cpp
```

After removal links should be added to the Wiki page created in #62.

(`matrix.*` turned out to have the useful symbolic Gauss elimination)

Added `integral.*` to the list, is completely unused, `integral` is a proper Python function.

**Comment by rwst** [comment]
@kcrisman @burcin @vbraun would like to have an opinion from at least one of you

**Comment by vbraun** [comment]
I don't mind removing stuff. My only concern is that it might make it more difficult to follow upstream. Though if you think that you can handle it then I'll believe you.

**Comment by kcrisman** [comment]
Hmm, good point.  What is the benefit for removing them here, rather than (say) in a script that installs it in Sage?  Especially if some of the Clifford or other stuff could potentially overlap/improve Sage functionality?  But I'm agnostic on it.

**Comment by rwst** [comment]
It's really annoying and confuses people coming new to the code. I don't know about others but I really had to analyze it all to see what's not used by Sage and so can be ignored. Lower the entry barrier, you can call it.

As to Clifford algebra there is `sage.algebras.clifford_algebra` and, looking at http://trac.sagemath.org/ticket/17096 the situation in Sage seems much better than a year ago. As to `color.cpp` it "implements the base elements and structure constants of the su(3) Lie algebra" which can be accessed in Sage via GAP. So, it's not that at some time we have to answer a question with "Oh yes we had that in Pynac but it got deleted".

As to following upstream, I already had to filter out diffs from files only in GiNaC by giving the command
```
git diff commit1 commit2 `cat pynac-files.txt`
```
or, gasp, do things by hand, when I previously ported patches from GiNaC.

**Comment by rwst** [comment]
So, since `matrix.*` and `symmetry.*` are actually used we are done with this task.
